"""Object type database for Doom entities.

Maps ViZDoom object names to gameplay-relevant info for AI agents.
"""

_DECORATION = {
    "type": "decoration",
    "threat": "none",
    "attack": "none",
    "speed": "static",
    "typical_hp": 0,
    "description": "Decoration. Ignore.",
}

OBJECT_INFO: dict[str, dict] = {
    # === MONSTERS ===
    "ZombieMan": {
        "type": "monster",
        "threat": "low",
        "attack": "hitscan",
        "speed": "slow",
        "typical_hp": 20,
        "description": "Former human with pistol. Weak hitscan, low HP. Drops Clip.",
    },
    "Zombieman": {  # alternate capitalization seen in-game
        "type": "monster",
        "threat": "low",
        "attack": "hitscan",
        "speed": "slow",
        "typical_hp": 20,
        "description": "Former human with pistol. Weak hitscan, low HP. Drops Clip.",
    },
    "ShotgunGuy": {
        "type": "monster",
        "threat": "medium",
        "attack": "hitscan",
        "speed": "slow",
        "typical_hp": 30,
        "description": "Former sergeant with shotgun. Dangerous hitscan burst at close range. Drops Shotgun.",
    },
    "ChaingunGuy": {
        "type": "monster",
        "threat": "medium",
        "attack": "hitscan",
        "speed": "slow",
        "typical_hp": 70,
        "description": "Former commando with chaingun. Rapid-fire hitscan, deadly in groups. Drops Chaingun.",
    },
    "DoomImp": {
        "type": "monster",
        "threat": "low",
        "attack": "projectile",
        "speed": "slow",
        "typical_hp": 60,
        "description": "Imp. Throws fireballs and has melee claw attack.",
    },
    "Demon": {
        "type": "monster",
        "threat": "medium",
        "attack": "melee",
        "speed": "medium",
        "typical_hp": 150,
        "description": "Pink Demon. Melee only but fast and tanky. Charges aggressively.",
    },
    "Spectre": {
        "type": "monster",
        "threat": "medium",
        "attack": "melee",
        "speed": "medium",
        "typical_hp": 150,
        "description": "Nearly invisible Demon. Same as Pinky but partially transparent.",
    },
    "LostSoul": {
        "type": "monster",
        "threat": "low",
        "attack": "melee",
        "speed": "medium",
        "typical_hp": 100,
        "description": "Flying skull. Charges at player as attack. Spawned by PainElemental.",
    },
    "Cacodemon": {
        "type": "monster",
        "threat": "medium",
        "attack": "projectile",
        "speed": "slow",
        "typical_hp": 400,
        "description": "Flying red sphere. Fires projectiles and has melee bite.",
    },
    "PainElemental": {
        "type": "monster",
        "threat": "medium",
        "attack": "projectile",
        "speed": "slow",
        "typical_hp": 400,
        "description": "Flying sphere that spawns LostSouls. Kill quickly to prevent spawns.",
    },
    "HellKnight": {
        "type": "monster",
        "threat": "medium",
        "attack": "projectile",
        "speed": "slow",
        "typical_hp": 500,
        "description": "Weaker Baron. Throws green fireballs and has melee attack.",
    },
    "BaronOfHell": {
        "type": "monster",
        "threat": "high",
        "attack": "projectile",
        "speed": "slow",
        "typical_hp": 1000,
        "description": "Tough bruiser. Green fireballs + strong melee. Very tanky.",
    },
    "Revenant": {
        "type": "monster",
        "threat": "high",
        "attack": "projectile",
        "speed": "medium",
        "typical_hp": 300,
        "description": "Skeleton with rockets. Fires HOMING missiles. Also punches in melee.",
    },
    "Arachnotron": {
        "type": "monster",
        "threat": "high",
        "attack": "projectile",
        "speed": "medium",
        "typical_hp": 500,
        "description": "Baby Spider. Rapid-fire plasma attack. Sustained fire is deadly.",
    },
    "Fatso": {
        "type": "monster",
        "threat": "high",
        "attack": "projectile",
        "speed": "slow",
        "typical_hp": 600,
        "description": "Mancubus. Triple fireball spread. Very tanky.",
    },
    "Archvile": {
        "type": "monster",
        "threat": "high",
        "attack": "projectile",
        "speed": "fast",
        "typical_hp": 700,
        "description": "PRIORITY TARGET. Resurrects dead monsters. Unavoidable flame attack (80 dmg). Kill first.",
    },
    "Cyberdemon": {
        "type": "monster",
        "threat": "high",
        "attack": "projectile",
        "speed": "fast",
        "typical_hp": 4000,
        "description": "Boss. 3 rockets per volley. Immune to splash damage. Extremely dangerous.",
    },
    "SpiderMastermind": {
        "type": "monster",
        "threat": "high",
        "attack": "hitscan",
        "speed": "medium",
        "typical_hp": 3000,
        "description": "Boss. Super chaingun hitscan. Immune to splash. Huge hitbox.",
    },
    # ViZDoom custom monsters
    "MarineChainsawVzd": {
        "type": "monster",
        "threat": "medium",
        "attack": "melee",
        "speed": "slow",
        "typical_hp": 100,
        "description": "Marine with chainsaw. Melee only. ViZDoom scenario enemy.",
    },
    "ScriptedMarine": {
        "type": "monster",
        "threat": "medium",
        "attack": "hitscan",
        "speed": "slow",
        "typical_hp": 100,
        "description": "Programmable marine NPC. Attack varies by variant.",
    },

    # === PROJECTILES (dodge these) ===
    "DoomImpBall": {
        "type": "projectile",
        "threat": "low",
        "attack": "none",
        "speed": "medium",
        "typical_hp": 0,
        "description": "Imp fireball. Dodge laterally.",
    },
    "BaronBall": {
        "type": "projectile",
        "threat": "medium",
        "attack": "none",
        "speed": "medium",
        "typical_hp": 0,
        "description": "Baron/HellKnight green fireball. Dodge laterally.",
    },
    "CacodemonBall": {
        "type": "projectile",
        "threat": "medium",
        "attack": "none",
        "speed": "medium",
        "typical_hp": 0,
        "description": "Cacodemon plasma ball.",
    },
    "RevenantTracer": {
        "type": "projectile",
        "threat": "high",
        "attack": "none",
        "speed": "medium",
        "typical_hp": 0,
        "description": "Revenant HOMING missile. Break line of sight to avoid.",
    },
    "ArachnotronPlasma": {
        "type": "projectile",
        "threat": "medium",
        "attack": "none",
        "speed": "fast",
        "typical_hp": 0,
        "description": "Arachnotron plasma bolt.",
    },
    "FatShot": {
        "type": "projectile",
        "threat": "medium",
        "attack": "none",
        "speed": "fast",
        "typical_hp": 0,
        "description": "Mancubus fireball. Fired in spread of 3.",
    },
    "Rocket": {
        "type": "projectile",
        "threat": "high",
        "attack": "none",
        "speed": "fast",
        "typical_hp": 0,
        "description": "Rocket projectile. Splash damage. Dodge laterally.",
    },
    "PlasmaBall": {
        "type": "projectile",
        "threat": "low",
        "attack": "none",
        "speed": "fast",
        "typical_hp": 0,
        "description": "Plasma rifle bolt.",
    },
    "BFGBall": {
        "type": "projectile",
        "threat": "high",
        "attack": "none",
        "speed": "fast",
        "typical_hp": 0,
        "description": "BFG projectile. 100 damage + spray. Run.",
    },

    # === HEALTH ===
    "HealthBonus": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+1 HP (up to 200).",
    },
    "Stimpack": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+10 HP (up to 100).",
    },
    "Medikit": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+25 HP (up to 100).",
    },
    "Soulsphere": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+100 HP (up to 200). High priority pickup.",
    },
    "Megasphere": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Sets HP=200, armor=200. Highest priority pickup.",
    },
    "Berserk": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Heals to 100 HP. 10x fist damage for rest of level.",
    },
    "CustomMedikit": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+20 HP. ViZDoom scenario item.",
    },
    "Poison": {
        "type": "item",
        "threat": "low",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "AVOID. Looks like HealthBonus but deals 30 damage on pickup.",
    },

    # === ARMOR ===
    "ArmorBonus": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+1 armor (up to 200).",
    },
    "GreenArmor": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "100 armor, absorbs 1/3 damage.",
    },
    "BlueArmor": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "200 armor, absorbs 1/2 damage. High priority.",
    },

    # === AMMO ===
    "Clip": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+10 bullets.",
    },
    "ClipBox": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+50 bullets.",
    },
    "Shell": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+4 shells.",
    },
    "ShellBox": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+20 shells.",
    },
    "RocketAmmo": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+1 rocket.",
    },
    "RocketBox": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+5 rockets.",
    },
    "Cell": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+20 cells (plasma/BFG).",
    },
    "CellPack": {
        "type": "ammo",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "+100 cells (plasma/BFG).",
    },

    # === WEAPONS ===
    "Chainsaw": {
        "type": "weapon",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Melee weapon. Rapid continuous damage.",
    },
    "Shotgun": {
        "type": "weapon",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "7 pellets, uses shells. Good all-around.",
    },
    "SuperShotgun": {
        "type": "weapon",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "20 pellets, 2 shells. Devastating close range.",
    },
    "Chaingun": {
        "type": "weapon",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Rapid-fire hitscan. Good for stun-locking.",
    },
    "RocketLauncher": {
        "type": "weapon",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "High damage + splash. Watch for self-damage at close range.",
    },
    "PlasmaRifle": {
        "type": "weapon",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Rapid plasma projectiles. High sustained DPS.",
    },
    "BFG9000": {
        "type": "weapon",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Devastating area damage. 40 cells per shot. Best weapon.",
    },

    # === PLAYER ===
    "DoomPlayer": {
        "type": "player",
        "threat": "none",
        "attack": "none",
        "speed": "medium",
        "typical_hp": 100,
        "description": "The player (self or other player in multiplayer).",
    },

    # === EFFECTS (ignore) ===
    "Blood": {
        "type": "decoration",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Blood splatter. Ignore.",
    },
    "BulletPuff": {
        "type": "decoration",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Bullet impact. Ignore.",
    },
    "TeleportFog": {
        "type": "decoration",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Teleport effect. Ignore.",
    },
    "PatrolPoint": {
        "type": "decoration",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Invisible waypoint. Ignore.",
    },

    # === KEYS ===
    "BlueCard": {
        "type": "key",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Blue keycard. Opens blue-locked doors. Pick up.",
    },
    "RedCard": {
        "type": "key",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Red keycard. Opens red-locked doors. Pick up.",
    },
    "YellowCard": {
        "type": "key",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Yellow keycard. Opens yellow-locked doors. Pick up.",
    },
    "BlueSkull": {
        "type": "key",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Blue skull key. Opens blue-locked doors. Pick up.",
    },
    "RedSkull": {
        "type": "key",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Red skull key. Opens red-locked doors. Pick up.",
    },
    "YellowSkull": {
        "type": "key",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Yellow skull key. Opens yellow-locked doors. Pick up.",
    },

    # === POWERUPS ===
    "Backpack": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Doubles all ammo capacity + gives some ammo. High priority.",
    },
    "Allmap": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Computer area map. Reveals entire automap.",
    },
    "Infrared": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Light amplification visor. Full brightness for 120 seconds.",
    },
    "BlurSphere": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Partial invisibility. Enemies aim poorly for 60 seconds.",
    },
    "RadSuit": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Radiation suit. Protects from floor damage for 60 seconds.",
    },
    "InvulnerabilitySphere": {
        "type": "item",
        "threat": "none",
        "attack": "none",
        "speed": "static",
        "typical_hp": 0,
        "description": "Invulnerability. 30 seconds of no damage. Highest priority.",
    },

    # === INTERACTIVE OBJECTS ===
    "ExplosiveBarrel": {
        "type": "hazard",
        "threat": "low",
        "attack": "none",
        "speed": "static",
        "typical_hp": 20,
        "description": "Exploding barrel. Shoot near enemies for splash damage. Don't stand near it.",
    },

    # === DECORATIONS (all ignorable) ===
    "BigTree": _DECORATION,
    "Column": _DECORATION,
    "TechPillar": _DECORATION,
    "TorchTree": _DECORATION,
    "Stalagtite": _DECORATION,
    "Candelabra": _DECORATION,
    "Candlestick": _DECORATION,
    "BlueTorch": _DECORATION,
    "GreenTorch": _DECORATION,
    "RedTorch": _DECORATION,
    "ShortBlueTorch": _DECORATION,
    "ShortGreenTorch": _DECORATION,
    "ShortRedTorch": _DECORATION,
    "TechLamp": _DECORATION,
    "TechLamp2": _DECORATION,
    "ShortGreenColumn": _DECORATION,
    "ShortRedColumn": _DECORATION,
    "TallGreenColumn": _DECORATION,
    "TallRedColumn": _DECORATION,
    "SkullColumn": _DECORATION,
    "HeartColumn": _DECORATION,
    "FloatingSkull": _DECORATION,
    "HeadOnAStick": _DECORATION,
    "BurningBarrel": _DECORATION,
    "LiveStick": _DECORATION,
    "DeadStick": _DECORATION,
    "Meat2": _DECORATION,
    "Meat5": _DECORATION,
    "NonsolidMeat2": _DECORATION,
    "NonsolidMeat4": _DECORATION,
    "NonsolidMeat5": _DECORATION,
    "NonsolidTwitch": _DECORATION,
    "HangTLookingDown": _DECORATION,
    "HangTNoBrain": _DECORATION,
    "HangTSkull": _DECORATION,
    "SmallBloodPool": _DECORATION,
    "BrainStem": _DECORATION,
    # Dead bodies
    "DeadMarine": _DECORATION,
    "DeadZombieMan": _DECORATION,
    "DeadShotgunGuy": _DECORATION,
    "DeadDemon": _DECORATION,
    "DeadCacodemon": _DECORATION,
    "DeadDoomImp": _DECORATION,
    "GibbedMarine": _DECORATION,
    "GibbedMarineExtra": _DECORATION,
    "Gibs": _DECORATION,
    "ColonGibs": _DECORATION,
    "DehackedPickup0": _DECORATION,
}

# Fallback for unknown objects
_UNKNOWN = {
    "type": "unknown",
    "threat": "none",
    "attack": "none",
    "speed": "static",
    "typical_hp": 0,
    "description": "Unknown object type.",
}


def get_object_info(name: str) -> dict:
    """Look up gameplay info for a ViZDoom object by name."""
    return OBJECT_INFO.get(name, {**_UNKNOWN, "description": f"Unknown object: {name}"})
